name: reverse_shell_generator
services:
  reverse_shell_generator:
    cpu_shares: 10
    command:
      - ""
    deploy:
      resources:
        limits:
          memory: 7937M
    image: vuldocker/reverse_shell_generator:latest
    labels:
      icon: https://camo.githubusercontent.com/0a9d866ea6aec774c89c411c34f4bdc8e4f4a72246f3e8995676d6f72266e205/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f70617472656f6e2e737667
    ports:
      - target: 80
        published: "18880"
        protocol: tcp
    restart: always
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: ""
      volumes:
        - container: /www
          description:
            en_us: ""
    volumes: []
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false

    container_name: ""
x-casaos:
  architectures:
    - amd64
  author: arch3rpro
  category: Pentest
  description:
    en_us: Hosted Reverse Shell generator with a ton of functionality. -- (Great for
      CTFs)
    zh_cn: 在线自动反弹shell命令生成器
  developer: 0dayCTF
  hostname: ""
  icon: https://camo.githubusercontent.com/0a9d866ea6aec774c89c411c34f4bdc8e4f4a72246f3e8995676d6f72266e205/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f70617472656f6e2e737667
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Adminer/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Adminer/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Adminer/screenshot-3.png
  index: /
  main: reverse_shell_generator
  port_map: "18880"
  scheme: http
  store_app_id: reverse_shell_generator
  tagline:
    en_us: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
    zh_cn: 在线自动反弹shell命令生成器
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Adminer/thumbnail.png
  tips:
    custom: Hosted Reverse Shell generator with a ton of functionality. -- (Great
      for CTFs)
  title:
    custom: ""
    en_us: Reverse_shell_generator
