name: reverse
services:
  reverse:
    container_name: reverse
    deploy:
      resources:
        limits:
          memory: 256M
    image: vuldocker/reverse_shell_generator:1.0.0
    labels:
      icon: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Reverse-shell-generator/Reverse-shell-generator.svg
    ports:
      - target: 80
        published: "18088"
        protocol: tcp
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    command: []
    environment: []
    network_mode: bridge
    privileged: false
    cpu_shares: 90
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: arch3rpro
  category: Pentest
  description:
    en_us: Hosted Reverse Shell generator with a ton of functionality. -- (Great for CTFs)
    zh_cn: 在线自动反弹shell命令生成器.
  developer: 0dayCTF
  icon: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Reverse-shell-generator/Reverse-shell-generator.svg
  port_map: "18088"
  store_app_id: reverse
    tagline:
    en_us:  Hosted Reverse Shell generator
    zh_cn: 在线自动反弹shell命令生成器
  title:
    custom: Reverse_shell_generator
  hostname: ""
  scheme: http
  index: /
