name: reverse_shell_generator
services:
  reverse_shell_generator:
    command:
      - ""
    image: vuldocker/reverse_shell_generator:latest
    labels:
      icon: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Reverse-shell-generator/Reverse-shell-generator.svg
    ports:
      - target: 80
        published: "10888"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/4bbaf841be911e2eba62f498a7b72ce308759fe9b4d5e17769bc800983cc6643/_data
        target: /www
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: ""
      volumes:
        - container: /www
          description:
            en_us: ""
    devices: []
    cap_add: []
    network_mode: default
    privileged: false
    container_name: ""
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 3876M
x-casaos:
  architectures:
    - amd64
  author: CasaOS User
  category: unknown
  description:
    en_us: ""
  developer: unknown
  icon: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Reverse-shell-generator/Reverse-shell-generator.svg
  main: lucid_einstein
  port_map: "10888"
  scheme: http
  store_app_id: lucid_einstein
  tagline:
    en_us: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  thumbnail: ""
  tips:
    custom: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  title:
    en_us: reverse_shell_generator
    custom: ""
  hostname: ""
  index: /
