name: nps
services:
  empire:
    image: vuldocker/nps:0.26.17
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped
    ports:
      - 8081:8081
      - 8024:8024
      - 18080:80
      - 18443:443
    x-casaos:
      ports:
        - container: "8081"
          description:
            en_us: NPS Server Web manager 
            zh_cn: NPS服务端管理端口
    container_name: nps
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime:ro
x-casaos:
  architectures:
    - amd64
  author: arch3rpro
  category: Pentest
  description:
    en_us: a lightweight, high-performance, powerful intranet penetration proxy server, with a powerful web management terminal.
    zh_cn: 一款轻量级、高性能、功能强大的内网穿透代理服务器。支持tcp、udp、socks5、http等几乎所有流量转发(本版本为yisier修改版，修复了API 鉴权漏洞).
  developer: yisier
  icon: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/NPS/nps.png
  screenshot_link:
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/NPS/screenshot-1.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/NPS/screenshot-2.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/NPS/screenshot-3.png
  tagline:
    en_us: Intranet penetration proxy server
    zh_cn: 内网穿透代理服务器
  thumbnail: https://raw.githubusercontent.com/arch3rPro/CasaOS-Pentest/main/Apps/NPS/thumbnail.png
  index: 
  scheme: http
  tips:
    custom: |-
      Host模式无法使用，添加反向代理，请修改容器映射端口号；
      默认Web端账号：admin 密码：123 请及时修改。
  title:
    custom: NPS
  port_map: "8081"