name: next-terminal
services:
  guacd:
    image: dushixiang/guacd:latest
    deploy:
      resources:
        limits:
          memory: 15917M
    restart: unless-stopped
    volumes:
      - type: bind
        source: /tmp/casaos-compose-app-3976183864/data
        target: /usr/local/next-terminal/data
    container_name: guacd
  next-terminal:
    image: dushixiang/next-terminal:latest
    deploy:
      resources:
        limits:
          memory: 15917M
    restart: unless-stopped
    depends_on:
      guacd:
        condition: service_started
        required: true
    environment:
      - DB=sqlite
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
    ports:
      - 8088:8088
    x-casaos:
      ports:
        - container: "8088"
          description:
            en_us: next-terminal
            zh_cn: next-terminal
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
      - type: bind
        source: /tmp/casaos-compose-app-3976183864/data
        target: /usr/local/next-terminal/data
    container_name: next-terminal
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: arch3rPro
  category: Pentest
  description:
    en_us: KunLun-M is a complete open source static white-box scanning tool that supports semantic scanning of PHP and JavaScript, basic security, component security scanning, and basic scanning of Chrome Ext\Solidity.
    zh_cn: KunLun-M是一个完全开源的静态白盒扫描工具，支持PHP、JavaScript的语义扫描，基础安全、组件安全扫描，Chrome Ext\Solidity的基础扫描。
  developer: LoRexxar
  icon: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Kunlun-M/Kunlun-M.png  
  screenshot_link:
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Kunlun-M/screenshot-01.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Kunlun-M/screenshot-02.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Kunlun-M/screenshot-03.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Kunlun-M/screenshot-04.png
  tagline:
    en_us: Source Code Security Audit
    zh_cn: 开源代码安全审计
  thumbnail: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/KunLun-M/screenshot-03.png
  index: /
  scheme: http
  tips:
    custom: |-
      默认账号admin:admin,登录后请修改密码！！
  title:
    custom: next-terminal
  port_map: "8088"