name: Acunetix
services:
  acunetix:
    image: quay.io/hiepnv/acunetix:15.2
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped
    ports:
      - 3443:3443
    x-casaos:
      ports:
        - container: "3443"
          description:
            en_us: Acunetix Web UI  Port
            zh_cn: Acunetix Web页面端口
    container_name: acunetix
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: arch3rpro
  category: Pentest
  description:
    en_us: Acunetix is an end-to-end web security scanner that offers a 360 view of an organization's security.
    zh_cn: Acunetix 是一款端到端的Web安全扫描器，可提供组织机构全方位的安全分析。
  developer: Invicti
  icon: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Acunetix/acunetix.svg
  screenshot_link:
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Acunetix/screenshot-01.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Acunetix/screenshot-02.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Acunetix/screenshot-03.png
  tagline:
    en_us: Web Application Security Scanner
    zh_cn: Web应用安全漏洞扫描器
  thumbnail: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Acunetix/thumbnail.png
  index: /
  port_map: "3443"
  scheme: https
  tips:
    custom: |-
      默认账号：admin@acu.com
      默认密码：Passw0rd!
      登录后，请及时修改密码！！！
  title:
    custom: acunetix
