name: empire
services:
  empire:
    image: vuldocker/empire:5.6.3
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped
    ports:
      - 1337:1337
      - 5000:5000
    x-casaos:
      ports:
        - container: "1337"
          description:
            en_us: PowerShell Empire Web UI 
            zh_cn: Empire Web 端口
    container_name: empire
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: arch3rpro
  category: Pentest
  description:
    en_us: Empire is a post-exploitation and adversary emulation framework that is used to aid Red Teams and Penetration Testers.
    zh_cn: Empire 是一个后渗透利用工具和仿真模拟框架，用于帮助红队和渗透测试人员.
  developer: BC-SECURITY
  icon: https://raw.githubusercontent.com/arch3rPro/CasaOS-Pentest/main/Apps/Empire/empire.svg
  screenshot_link:
    - https://raw.githubusercontent.com/arch3rPro/CasaOS-Pentest/main/Apps/Empire/screenshot-1.jpg
    - https://raw.githubusercontent.com/arch3rPro/CasaOS-Pentest/main/Apps/Empire/screenshot-2.jpg
    - https://raw.githubusercontent.com/arch3rPro/CasaOS-Pentest/main/Apps/Empire/screenshot-3.jpg
  tagline:
    en_us:  Post-exploitation framework
    zh_cn: PowerShell攻击载荷渗透攻击框架
  thumbnail: https://raw.githubusercontent.com/arch3rPro/CasaOS-Pentest/main/Apps/Empire/thumbnail.png
  index: /index.html
  scheme: http
  title:
    custom: empire
  port_map: "1337"